@baseUrl = http://localhost:5000
@urlPath = api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3NTM4OWI5MWQ0MGRmYWU4OTU1N2UiLCJlbWFpbCI6ImNvbmd0dXF3ZUBnbWFpbC5jb20iLCJpYXQiOjE3MDAyMjE4MzMsImV4cCI6MTcwMDMwODIzM30.rTqaC_ZqqQP9IM19tG48wzHTXuAKuk2OHpR03FgC2BA

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "duyhau1",
  "password": "12345678",
  "email": "congtuzxc1@gmail.com"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "account": "duyhau1",
  "password": "12345678"
}

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": ""
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/<token>
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "",
  "confirmPassword": ""
}
